-- MySQL Script generated by MySQL Workbench
-- 11/05/14 03:56:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema printer_authentication
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema printer_authentication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `printer_authentication` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `printer_authentication` ;

-- -----------------------------------------------------
-- Table `printer_authentication`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_authentication`.`users` ;

CREATE TABLE IF NOT EXISTS `printer_authentication`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `salted_password` VARCHAR(255) NOT NULL,
  `salt` BIGINT(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;

USE `printer_authentication` ;

-- -----------------------------------------------------
-- procedure add_user
-- -----------------------------------------------------

USE `printer_authentication`;
DROP procedure IF EXISTS `printer_authentication`.`add_user`;

DELIMITER $$
USE `printer_authentication`$$

CREATE PROCEDURE `printer_authentication`.`add_user` (IN username Varchar(255), IN pass Varchar(255))
BEGIN
    declare random BigInt(8);
    declare saltedPassword Varchar(255);
    set random = rand()*pow(2,64);
    set saltedPassword = sha2(CONCAT(pass,random),512);
    INSERT INTO users VALUES (0,username,saltedPassword,random);
END
$$

DELIMITER ;

-- -----------------------------------------------------
-- function authenticate_message
-- -----------------------------------------------------

USE `printer_authentication`;
DROP function IF EXISTS `printer_authentication`.`authenticate_message`;

DELIMITER $$
USE `printer_authentication`$$



CREATE FUNCTION `printer_authentication`.`authenticate_message` (username VARCHAR(255), msgHash varchar(255), fullHash VARCHAR(255)) 
RETURNS boolean
BEGIN
	DECLARE pass VARCHAR(255);
    DECLARE message VARCHAR(255);
	SET pass = (SELECT salted_password FROM users WHERE users.username = username);
    set message =  sha2(CONCAT(msgHash,username,pass),512);
    return message = fullHash;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_salt
-- -----------------------------------------------------

USE `printer_authentication`;
DROP function IF EXISTS `printer_authentication`.`get_salt`;

DELIMITER $$
USE `printer_authentication`$$



CREATE FUNCTION `printer_authentication`.`get_salt` (username VARCHAR(255)) 
RETURNS BigInt(8)
BEGIN
    return (SELECT salt FROM users WHERE users.username = username);
END$$

DELIMITER ;
SET SQL_MODE = '';
GRANT USAGE ON *.* TO printer_server;
 DROP USER printer_server;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'printer_server' IDENTIFIED BY 'password';

GRANT EXECUTE ON function `printer_authentication`.`authenticate_message` TO 'printer_server';
GRANT EXECUTE ON function `printer_authentication`.`get_salt` TO 'printer_server';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
